name: powergym
description: "PowerGym - Athlete Management App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  sqflite: ^2.4.2
  path: ^1.9.1
  provider: ^6.1.2
  google_fonts: ^6.2.1
  intl: ^0.20.2
  image_picker: ^1.1.2
  shared_preferences: ^2.3.4
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  http: ^1.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/dash.jpg
    - assets/welcome_bg.jpg
